In scripts, print errors to stdout

diff --git a/refresh-dashboard b/refresh-dashboard
--- a/refresh-dashboard
+++ b/refresh-dashboard
@@ -1,9 +1,9 @@
 #!/bin/sh
 
 if [ ! -f psm-dashboard-config.json ]; then
-  echo "ERROR: You have no 'psm-dashboard-config.json' file."
-  echo "       Please copy 'psm-dashboard-config.json.tmpl' to"
-  echo "       that name, edit as needed, and try again."
+  echo "ERROR: You have no 'psm-dashboard-config.json' file." >&2
+  echo "       Please copy 'psm-dashboard-config.json.tmpl' to" >&2
+  echo "       that name, edit as needed, and try again." >&2
   exit 1
 fi
 
diff --git a/reqs2csv b/reqs2csv
--- a/reqs2csv
+++ b/reqs2csv
@@ -1,9 +1,9 @@
 #!/bin/sh
 
 if [ "`which xlsx2csv`"x = "x" ]; then
-  echo "ERROR: You need to have xlsx2csv installed."
-  echo "       You can do 'pip3 install xlsx2csv' or get it"
-  echo "       from https://github.com/dilshod/xlsx2csv."
+  echo "ERROR: You need to have xlsx2csv installed." >&2
+  echo "       You can do 'pip3 install xlsx2csv' or get it" >&2
+  echo "       from https://github.com/dilshod/xlsx2csv." >&2
   # Some other choices for XLSX-to-CSV conversion are:
   # 
   #   - github.com/staale/py-xlsx
@@ -17,9 +17,9 @@ if [ "`which xlsx2csv`"x = "x" ]; then
 fi
 
 if [ ! -f psm-dashboard-config.json ]; then
-  echo "ERROR: You have no 'psm-dashboard-config.json' file."
-  echo "       Please copy 'psm-dashboard-config.json.tmpl' to"
-  echo "       that name, edit as needed, and try again."
+  echo "ERROR: You have no 'psm-dashboard-config.json' file." >&2
+  echo "       Please copy 'psm-dashboard-config.json.tmpl' to" >&2
+  echo "       that name, edit as needed, and try again." >&2
   exit 1
 fi
 
@@ -33,19 +33,19 @@ cd ${RTM_XLSX_DIR}
 RTM_XLSX_DIR_BRANCH=`git branch | grep '^* ' | cut -c3-`
 cd ${SAVED_CWD}
 if [ "${RTM_XLSX_DIR_BRANCH}" != "master" ]; then
-  echo "ERROR: PSM tree is not on 'master' branch"
-  echo ""
-  echo "Your PSM repository clone must be on the 'master' branch, so"
-  echo "that we get the right version of the requirements spreadsheet."
+  echo "ERROR: PSM tree is not on 'master' branch" >&2
+  echo "" >&2
+  echo "Your PSM repository clone must be on the 'master' branch, so" >&2
+  echo "that we get the right version of the requirements spreadsheet." >&2
   exit 1
 fi
 
 if [ ! -f "${RTM_XLSX}" ]; then
-  echo "ERROR: can't find RTM.xlsx"
-  echo ""
-  echo "You must set the 'psm_reqs' parameter in 'psm-dashboard-config.json'"
-  echo "to point to the requirements/RTM.xlsx spreadsheet that lives in"
-  echo "the PSM tree."
+  echo "ERROR: can't find RTM.xlsx" >&2
+  echo "" >&2
+  echo "You must set the 'psm_reqs' parameter in 'psm-dashboard-config.json'" >&2
+  echo "to point to the requirements/RTM.xlsx spreadsheet that lives in" >&2
+  echo "the PSM tree." >&2
   exit 1
 fi
 
